const all_purchase_orders = [
  {
    "closedPo": "0",
    "partReceived": "0",
    "bookedIn": "0",
    "isStrategic": "0",
    "priceChanged": "0",
    "newProduct": "0",
    "stockMessage": "Due today",
    "EAN": "8806090843242",
    "supplier": "SmartCom Bayern GmbH",
    "supplierPartNumber": "EF-NG991PBEGEE",
    "productId": "83905",
    "productName": "Official Samsung Galaxy S21 LED View Cover Case - Black",
    "currency": "EUR",
    "ukEquiv": "24.75",
    "exchangeRate": "0.85643",
    "cost": "28.90",
    "eta": "07/04/2021",
    "rawEta": "2021-04-07",
    "notes": "",
    "chaseDate": null,
    "rawChaseDate": null,
    "orderDate": "23/03/2021",
    "rawOrderDate": "2021-03-23 17:37:29",
    "orderQty": "10",
    "receivedValue": "0",
    "poNumber": "97876",
    "polNumber": "774853",
    "bookedInDate": null,
    "rawBookedInDate": null,
    "stockMessageId": "100",
    "liveStockLevel": "0",
    "availableStockLevel": "0",
    "orderDetailId": null,
    "rawEtaChangeCount": "0"
  },
  {
    "closedPo": "0",
    "partReceived": "0",
    "bookedIn": "0",
    "isStrategic": "1",
    "priceChanged": "0",
    "newProduct": "0",
    "stockMessage": "In stock",
    "EAN": "8806090022661",
    "supplier": "SmartCom Bayern GmbH",
    "supplierPartNumber": "EE-UC10JUWEGWW",
    "productId": "75804",
    "productName": "Official Samsung USB-C To 3.5mm Audio Aux Headphone Adapter - White",
    "currency": "EUR",
    "ukEquiv": "4.88",
    "exchangeRate": "0.85643",
    "cost": "5.70",
    "eta": "30/03/2021",
    "rawEta": "2021-03-30",
    "notes": "",
    "chaseDate": null,
    "rawChaseDate": null,
    "orderDate": "23/03/2021",
    "rawOrderDate": "2021-03-23 17:37:29",
    "orderQty": "25",
    "receivedValue": "0",
    "poNumber": "97876",
    "polNumber": "774848",
    "bookedInDate": null,
    "rawBookedInDate": null,
    "stockMessageId": "9",
    "liveStockLevel": "44",
    "availableStockLevel": "44",
    "orderDetailId": null,
    "rawEtaChangeCount": "1"
  },
  {
    "closedPo": "0",
    "partReceived": "0",
    "bookedIn": "0",
    "isStrategic": "1",
    "priceChanged": "0",
    "newProduct": "0",
    "stockMessage": "In stock",
    "EAN": "8801790032194",
    "supplier": "SmartCom Bayern GmbH",
    "supplierPartNumber": "GP-TOU020SAABW",
    "productId": "83631",
    "productName": "Official Samsung Bluetooth Selfie Stick With Tripod - Black",
    "currency": "EUR",
    "ukEquiv": "13.70",
    "exchangeRate": "0.85643",
    "cost": "16.00",
    "eta": "30/03/2021",
    "rawEta": "2021-03-30",
    "notes": "",
    "chaseDate": null,
    "rawChaseDate": null,
    "orderDate": "23/03/2021",
    "rawOrderDate": "2021-03-23 17:37:29",
    "orderQty": "10",
    "receivedValue": "0",
    "poNumber": "97876",
    "polNumber": "774851",
    "bookedInDate": null,
    "rawBookedInDate": null,
    "stockMessageId": "9",
    "liveStockLevel": "5",
    "availableStockLevel": "5",
    "orderDetailId": null,
    "rawEtaChangeCount": "1"
  },
  {
    "closedPo": "0",
    "partReceived": "0",
    "bookedIn": "0",
    "isStrategic": "0",
    "priceChanged": "0",
    "newProduct": "0",
    "stockMessage": "In stock",
    "EAN": "8806090029295",
    "supplier": "SmartCom Bayern GmbH",
    "supplierPartNumber": "EF-PN975TWEGWW",
    "productId": "74478",
    "productName": "Official Samsung Galaxy Note 10 Plus Silicone Cover Case - White",
    "currency": "EUR",
    "ukEquiv": "5.82",
    "exchangeRate": "0.85643",
    "cost": "6.80",
    "eta": "30/03/2021",
    "rawEta": "2021-03-30",
    "notes": "",
    "chaseDate": null,
    "rawChaseDate": null,
    "orderDate": "23/03/2021",
    "rawOrderDate": "2021-03-23 17:37:29",
    "orderQty": "5",
    "receivedValue": "0",
    "poNumber": "97876",
    "polNumber": "774854",
    "bookedInDate": null,
    "rawBookedInDate": null,
    "stockMessageId": "9",
    "liveStockLevel": "2",
    "availableStockLevel": "2",
    "orderDetailId": null,
    "rawEtaChangeCount": "1"
  },
  {
    "closedPo": "0",
    "partReceived": "0",
    "bookedIn": "0",
    "isStrategic": "1",
    "priceChanged": "0",
    "newProduct": "0",
    "stockMessage": "Due today",
    "EAN": "8806090639579",
    "supplier": "SmartCom Bayern GmbH",
    "supplierPartNumber": "EJ-PN980BAEGEU",
    "productId": "81612",
    "productName": "Official Samsung Galaxy Note 20 / Note 20 Ultra S Pen Stylus - Bronze",
    "currency": "EUR",
    "ukEquiv": "15.84",
    "exchangeRate": "0.85643",
    "cost": "18.50",
    "eta": "30/03/2021",
    "rawEta": "2021-03-30",
    "notes": "",
    "chaseDate": null,
    "rawChaseDate": null,
    "orderDate": "23/03/2021",
    "rawOrderDate": "2021-03-23 17:37:29",
    "orderQty": "13",
    "receivedValue": "0",
    "poNumber": "97876",
    "polNumber": "774849",
    "bookedInDate": null,
    "rawBookedInDate": null,
    "stockMessageId": "100",
    "liveStockLevel": "0",
    "availableStockLevel": "0",
    "orderDetailId": null,
    "rawEtaChangeCount": "1"
  },
  {
    "closedPo": "0",
    "partReceived": "0",
    "bookedIn": "0",
    "isStrategic": "0",
    "priceChanged": "0",
    "newProduct": "0",
    "stockMessage": "In stock",
    "EAN": "8801643651268",
    "supplier": "SmartCom Bayern GmbH",
    "supplierPartNumber": "EF-ZG975CWEGWW",
    "productId": "70641",
    "productName": "Official Samsung Galaxy S10 Plus Clear View Cover Case - White",
    "currency": "EUR",
    "ukEquiv": "14.13",
    "exchangeRate": "0.85643",
    "cost": "16.50",
    "eta": "30/03/2021",
    "rawEta": "2021-03-30",
    "notes": "",
    "chaseDate": null,
    "rawChaseDate": null,
    "orderDate": "23/03/2021",
    "rawOrderDate": "2021-03-23 17:37:29",
    "orderQty": "5",
    "receivedValue": "0",
    "poNumber": "97876",
    "polNumber": "774852",
    "bookedInDate": null,
    "rawBookedInDate": null,
    "stockMessageId": "9",
    "liveStockLevel": "4",
    "availableStockLevel": "4",
    "orderDetailId": null,
    "rawEtaChangeCount": "2"
  },
]

export default all_purchase_orders;